version: '3.8'

services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - AUTH_SERVICE_URL=http://auth-service:3001
      - PROPERTY_SERVICE_URL=http://property-service:3002
      - MESSAGING_SERVICE_URL=http://messaging-service:3003
      - MONGODB_URI=mongodb://mongodb:27017
    networks:
      - app-network
    depends_on:
      - auth-service
      - property-service
      - messaging-service
    volumes:
      - ./services/api-gateway:/app
      - /app/node_modules

  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/auth-db
    networks:
      - app-network
    depends_on:
      - mongo
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules

  property-service:
    build: ./services/property-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGODB_URI=mongodb://mongodb:27017/property-db
      - AUTH_SERVICE_URL=http://auth-service:3001
    networks:
      - app-network
    depends_on:
      - mongo
      - auth-service
    volumes:
      - ./services/property-service:/app
      - /app/node_modules

  messaging-service:
    build: ./services/messaging-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - MONGODB_URI=mongodb://mongodb:27017/messaging-db
      - AUTH_SERVICE_URL=http://auth-service:3001
      - PROPERTY_SERVICE_URL=http://property-service:3002
    networks:
      - app-network
    depends_on:
      - mongo
      - auth-service
    volumes:
      - ./services/messaging-service:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  app-network:
    external: true
